---
# handlers file

- name: restart plex-media-server
  service:
    name: plexmediaserver
    state: restarted
    enabled: yes
  become: yes

- name: restart openresty
  service:
    name: openresty
    state: restarted
    enabled: yes
  become: yes

- name: restart pi-hole-server
  service:
    name: pihole-ftl
    state: restarted
    enabled: yes
  become: yes

- name: restart pihole-ftl
  service:
    name: pihole-ftl
    state: restarted
    enabled: yes
  become: yes

- name: restart cloudflared-bin
  service:
    name: cloudflared@cloudflared
    state: restarted
    enabled: yes
  become: yes

- name: restart mongodb-bin
  service:
    name: mongodb
    state: restarted
    enabled: yes
  become: yes

- name: restart unifi
  service:
    name: unifi
    state: restarted
    enabled: yes
  become: yes


# AUR packages without any service that needs to be restarted
- name: restart rar
  shell: echo "no service to restart"

- name: restart python-cheetah3
  shell: echo "no service to restart"
