---
# handlers file

- name: restart plex-media-server
  service:
    name: plexmediaserver
    state: restarted
    enabled: yes
  become: yes

- name: restart openresty
  service:
    name: openresty
    state: restarted
    enabled: yes
  become: yes

- name: restart pi-hole-server
  service:
    name: pi-hole-server
    state: restarted
    enabled: yes
  become: yes

- name: restart pihole-FTL
  service:
    name: pihole-FTL
    state: restarted
    enabled: yes
  become: yes

- name: restart cloudflared
  service:
    name: cloudflared
    state: restarted
    enabled: yes
  become: yes

- name: restart rar
  shell: echo "no service to restart"
