---
# Configure a base Arch system from scratch.
- hosts: lan
  roles:
    - base
  tags: base

# Install specified AUR packages on hosts
# Packages are specified in host_vars
- hosts:
    - www.lan.myrveln.se
    - jenkins.lan.myrveln.se
  roles:
    - aur-pkg-upgrade
  tags: aur

# Distribute certificates to hosts
- hosts: certs
  roles:
    - distribute-certificate
  vars_files:
    - inventory/group_vars/all/vault.yml
  tags: certs
