---
- name: restart paccache
  ansible.builtin.service:
    name: paccache.timer
    state: restarted
  become: yes

- name: restart journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
  become: yes

- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: yes
