cert_install_dir: /etc/ssl/private/lan.myrveln.se
cert_files:
  - cert.pem
  - privkey.pem
  - fullchain.pem
  - chain.pem
cert_domain: lan.myrveln.se
jenkins_base_url: "https://jenkins.lan.myrveln.se"
