---
# Configure journal
- name: journal | create journal config directory
  file:
    path: /etc/systemd/journald.conf.d
    state: directory
  become: yes
  tags:
    - journal

- name: journal | push journal max size config
  template:
    src: 00-journal-size.conf.j2
    dest: /etc/systemd/journald.conf.d/00-journal-size.conf
  when: journal is defined and journal.max_size is defined
  notify:
    - restart journald
  become: yes
  tags:
    - journal
