---
- name: base | copy pacman configuration file based on architecture
  copy:
    src: "{{ pacman_config_map[ansible_facts['architecture']] }}"
    dest: /etc/pacman.conf
  become: yes
  when: ansible_facts['architecture'] in pacman_config_map
  vars:
    pacman_config_map:
      x86_64: pacman.x86_64.conf
      armv7l: pacman.armv7l.conf

- name: base | refresh pacman mirrors
  pacman:
    update_cache: yes
  become: yes
  register: refresh
  tags: upgrade

- name: base | upgrade packages on system
  pacman:
    update_cache: yes
    upgrade: yes
  become: yes
  register: upgraded_packages
  when: refresh is changed
  tags: upgrade

- name: base | show upgraded packages
  debug:
    msg: "{{ upgraded_packages.packages }}"
  when: upgraded_packages is changed
  tags: upgrade

- name: base | enable configured locales
  template:
    src: locale.gen
    dest: /etc/locale.gen
    owner: root
    group: root
    mode: 0644
  become: yes
  register: locale

- name: base | add /etc/locale.conf to the system
  copy:
    src: locale.conf
    dest: /etc/locale.conf
    owner: root
    group: root
  become: yes

- name: base | generate the locale files
  command: locale-gen
  become: yes
  when: locale is changed

- name: base | symlink the local time
  file:
    src: /usr/share/zoneinfo/Europe/Stockholm
    dest: /etc/localtime
  become: yes

- name: base | .ssh directory for user
  file:
    path: /home/{{ user.name }}/.ssh
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0700

- name: base | add ssh.public_keys to authorized_keys
  lineinfile:
    path: /home/{{ user.name }}/.ssh/authorized_keys
    state: present
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0600
    line: "{{ item }}"
  with_items:
    - "{{ ssh.public_keys }}"
  when: ssh is defined and ssh.public_keys is defined

- name: base | set hostname using systemd if inventory_hostname is not an IP
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd
  become: yes
  when: not (inventory_hostname is match('^(\d{1,3}\.){3}\d{1,3}$'))
  register: hostname_result

# - name: base | refresh facts only if hostname was changed
#   ansible.builtin.setup:
#     gather_subset:
#       - network
#       - hostname
#   become: yes
#   when: hostname_result is changed

- name: base | template the /etc/hosts
  template:
    src: hosts.j2
    dest: "/etc/hosts"
    owner: root
    group: root
    mode: 0644
  become: yes
  when: not (inventory_hostname is match('^(\d{1,3}\.){3}\d{1,3}$'))

# Include sub tasks
- include_tasks: shell.yml
  tags: [base,shell]

- include_tasks: sudo.yml
  tags: [base,sudo]

- include_tasks: packages.yml
  tags: [base,packages]

- include_tasks: journal.yml
  tags: [base,journal]
