---
# Configure environment and install pacman packages
- name: shell | install bash, bash-completion and emacs-nox
  community.general.pacman:
    name:
        - bash
        - bash-completion
        - emacs-nox
    state: present
  become: yes

- name: shell | download dotfiles from github to user ~/
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/myrveln/dotfiles/master/{{ item }}
    dest: "/home/{{ user.name }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0755
  with_items:
    - ".bash_profile"
    - ".aliases"
    - ".bashrc"

- name: shell | download dotfiles from github to root ~/
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/myrveln/dotfiles/master/{{ item }}
    dest: "/root/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - ".bash_profile"
    - ".aliases"
    - ".bashrc"
  become: yes

- name: shell | check state of ~/.config/emacs/themes for user
  ansible.builtin.file:
    path: "/home/{{ user.name }}/.config/emacs/themes"
    mode: 0775
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: directory

- name: shell | check state of ~/.config/emacs/themes for root
  ansible.builtin.file:
    path: "/root/.config/emacs/themes"
    mode: 0775
    owner: "root"
    group: "root"
    state: directory
  become: yes

- name: shell | download emacs config from github to user ~/
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/myrveln/dotfiles/master/.config/emacs/{{ item }}
    dest: "/home/{{ user.name }}/.config/emacs/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0644
  with_items:
    - "themes/afternoon-theme.el"
    - "init.el"

- name: shell | download emacs config from github to root ~/
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/myrveln/dotfiles/master/.config/emacs/{{ item }}
    dest: "/root/.config/emacs/{{ item }}"
    owner: "root"
    group: "root"
    mode: 0644
  with_items:
    - "themes/afternoon-theme.el"
    - "init.el"
  become: yes
