---
# Install and configure sudo
- name: sudo | install sudo
  community.general.pacman:
    name: sudo
    state: present
  become: yes

- name: sudo | add user to groups
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: "{{ item }}"
    append: yes
  with_items:
    - wheel
    - storage
    - power
  become: yes

- name: sudo | copy custom sshd drop-in
  ansible.builtin.template:
    src: 00-custom-sshd.conf
    dest: /etc/ssh/sshd_config.d/00-custom-sshd.conf
    mode: 0600
  notify:
    - restart sshd
  become: yes

- name: sudo | copy wheel sudoers drop-in
  ansible.builtin.template:
    src: 00-custom-sudoers-wheel.j2
    dest: /etc/sudoers.d/00-allow-wheel
    mode: 0600
    validate: "visudo -cf %s"
  become: yes
