---
ansible_python_interpreter: /usr/bin/python
ansible_connection: ssh

user:
    name: kim
    uid: 1000
    group: users
    gid: 100

languages:
    enabled:
        - "sv_SE.UTF-8 UTF-8"
        - "en_GB.UTF-8 UTF-8"

journal:
    max_size: 200M

ssh:
    public_keys:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCc3724+7/v0qON9u8Q+EDcIPQZR7vLFLu9wPx3uMLeHpzdvO/uVo2gu2cd3M/1CTKeLHx580PuBkxe+hN86uLFrM/KPiYazo+EK5sl/4GDRwL+XVFdBg+ugley92X/DAWcvA4JzKuwtUZ0o3V2wd1MedEhZ8Y7rz7F4XzvLXqxpaV5/fzpPFu8FG5qaYJJ9Zjnyg1u//0pFgV2Mmq2o+WV0mg8AeA5ufgbpmAqPIIJpQHvbzfb23bCW7P9GkqEEe5COhH/o7MomnWPnuI08VrIMYC9MivPPWUyo6ohySX6/+Ack0X4M3xnJ7GsuVN9F1NCeI2da0ms7zzkOE8neYZj kim@myrveln.se"
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzRp1uvvfNQMNsirTS5ItHQDCws+Ygw4GglQCBwUf9Q1Zo9+zEtA1NT05ETyRrEiHMPJ/C5eQ816ZP5p2xFKMOwVxkrzwRxUHyw6PzrBo559jKex9Iwei0IaOZCgNohaCbXGEte99eIyNBIjh4EfU+PiLQjiwOZO40H+ptyGantpLNIsYqjbUAJAv8NC/0wQ3DTd4iXgiZ1bZwSSr35m1Id2jkBLh2Ix9/wMIsHwyfNALpGTq0k1iVLJDSQOLP5Br+QUNJL/IVV2Pe8IkhQXu56cIYikHHeuYFZy1jVCNaEXTWI20LNDaFcnkrO2Ew4WBFp8QGgYfl23zqwqNF4M/9 jenkins@jenkins"

base_packages:
    - base-devel
    - binutils
    - coreutils
    - git
    - inetutils
    - jq
    - less
    - lsof
    - openssh
    - pacman-contrib
    - rsync
    - screen
    - sysstat
    - unzip
    - zip
